authors:
  tomsunic:
    name: Tomislav Sunić, Ph.D.
    description: Writer and former Croatian diplomat
    avatar: https://github.com/tomsunic.png
  alaindebenoist:
    name: Alain de Benoist
    description: French writer and founder of the New Right
    avatar: https://github.com/alaindebenoist.png
